apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name:  flagger-loadtester
spec:
  podSelector:
    matchLabels:
      app: loadtester
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: flagger-loadtester.pipeline-gamma.svc.cluster.local
  backends:
  - virtualService:
      virtualServiceRef:
        name: sample-app
  - virtualService:
      virtualServiceRef:
        name: sample-app-canary
  logging:
    accessLog:
      file:
        path: /dev/stdout


